environments:
  dev:
    values:
      - environments/dev.yaml
  stage:
    values:
      - environments/stage.yaml

---

releases:
  - name: hello-app
    namespace: default
    chart: ./hello-app
    values:
      - hello-app/values.yaml


