apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                   name: hello-secret
                   key: SECRET_VALUE