name: Deploy App

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy with Helmfile
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          HELM_VERSION=3.12.3
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh -v v${HELM_VERSION}

      - name: Install Helmfile
        run: |
          HELMFILE_VERSION=0.159.0
          wget https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz
          tar -xzf helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/helmfile

      - name: Init Helmfile Plugins
        run: |
          export HELMFILE_HELM3=true
          export HELM_INSTALL_HELMFILE_PLUGINS=true
          yes | helmfile init

      - name: Install SOPS
        run: |
          curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          sudo mv sops /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops
         
      - name: Set up SOPS Age Key
        run: |
          mkdir -p ~/.config/sops/age
          echo '${{ secrets.SOPS_AGE_KEY }}' > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name demo-eks-custom --region us-east-1

      - name: Init helmfile
        run: |
          helmfile init

      - name: List helmfile
        run: |
          helmfile --file deployments/helmfile.yaml list

      - name: Deploy with Helmfile
        working-directory: deployments
        run: |
          helmfile -e dev apply
