name: Deploy App

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy with Helmfile
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm & Helmfile
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          HELMFILE_VERSION=0.153.0
          curl -L https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_linux_amd64.tar.gz | tar xz
          sudo mv helmfile /usr/local/bin/
          helm plugin install https://github.com/jkroepke/helm-secrets

      - name: Set up SOPS Age Key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name demo-eks-custom --region us-east-1

      - name: Deploy with Helmfile
        working-directory: deployments
        run: |
          helmfile -e dev apply
